version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_db
    ports:
      - "6333:6333" # Cổng API chính
      - "6334:6334" # Cổng nội bộ
    volumes:
      - ./qdrant_storage:/qdrant/storage:z # Lưu dữ liệu bền vững (Persistence)
    restart: always